
package com.qwt.webservice.looselycoupledclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://server.webservice.qwt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server.webservice.qwt.com/", className = "com.qwt.webservice.looselycoupledclient.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.webservice.qwt.com/", className = "com.qwt.webservice.looselycoupledclient.AddResponse")
    @Action(input = "http://server.webservice.qwt.com/IMyService/addRequest", output = "http://server.webservice.qwt.com/IMyService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://server.webservice.qwt.com/", className = "com.qwt.webservice.looselycoupledclient.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://server.webservice.qwt.com/", className = "com.qwt.webservice.looselycoupledclient.MinusResponse")
    @Action(input = "http://server.webservice.qwt.com/IMyService/minusRequest", output = "http://server.webservice.qwt.com/IMyService/minusResponse")
    public int minus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param userId
     * @return
     *     returns com.qwt.webservice.looselycoupledclient.User
     */
    @WebMethod
    @WebResult(name = "userResult", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://server.webservice.qwt.com/", className = "com.qwt.webservice.looselycoupledclient.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://server.webservice.qwt.com/", className = "com.qwt.webservice.looselycoupledclient.GetUserResponse")
    @Action(input = "http://server.webservice.qwt.com/IMyService/getUserRequest", output = "http://server.webservice.qwt.com/IMyService/getUserResponse")
    public User getUser(
        @WebParam(name = "userId", targetNamespace = "")
        String userId);

}
